# application.yml
server:
  port: 8080

spring:
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOriginPatterns: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - PATCH
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true
      routes:
        - id: auth-service
          uri: http://localhost:8081
          predicates:
            - Path=/auth/**, /users/**

        - id: board-service
          uri: http://localhost:8082
          predicates:
            - Path=/board/**, /column/**, /task/**

        - id: notification-service
          uri: ws://localhost:8083
          predicates:
            - Path=/ws-endpoint/**

jwt:
  secret: 9f3a1c7e2b6d4f809a5c1e7b3d8f2a6c4b0e9d1f7a3c5e8b2d6f1a9c4e7b3d0